# These are supported funding model platforms

github: [Knight-Witch]
patreon: TheKnightWitch
ko_fi: knightwitch
custom: ['https://www.paypal.com/paypalme/KnightWitch', 'https://knightwitchapparel.com/']
